### PR TITLE
Remove trailing slashes from codeception paths

### PR DESCRIPTION
**Pull request by k4emic**
- Developer(s): @k4emic

- Ticket: https://spryker.atlassian.net/browse/APPS-4625 (unrelated, discovered while working on it)

- Docs PR: N/A

- Release Group: N/A

- merge: merge

#### Release Table

   Module                | Release Type         | Constraint Updates         |
   :--------------------- | :------------------------ | :--------------------- |
   SprykSrc              | patch {skip} (currently 0.0.x)  |                       |

---
This is a quality-of-life change for running tests more easily. There are no functional changes to the project.

Running individual test files doesn't currently work. This means we have to run the entire test suite while working on a specific topic.

```
php vendor/bin/codecept run tests/SprykerSdkTest/Spryk/Integration/Glue/AddGlueResourceMethodResponseTest.php -q

In Run.php line 643:
                              
  Test file can't be matched  

```                           

If the test path contains double slashes, it works:
```
php vendor/bin/codecept run tests//SprykerSdkTest/Spryk/Integration/Glue/AddGlueResourceMethodResponseTest.php -q


Time: 00:15.626, Memory: 60.50 MB

OK (6 tests, 165 assertions)

```

The regex pattern on this line indicates that slashes should not be included in the test path: https://github.com/Codeception/Codeception/blob/4.2.1/src/Codeception/Command/Run.php#L640

The official docs does not use trailing slashes in the example: https://codeception.com/docs/reference/Configuration#paths

Removing the trailing slash allows us to run individual tests
```
php vendor/bin/codecept run tests/SprykerSdkTest/Spryk/Integration/Glue/AddGlueResourceMethodResponseTest.php -q


Time: 00:15.568, Memory: 60.50 MB

OK (6 tests, 165 assertions)

```

### CODE REVIEW

**Comment by dereuromark** [comment]
Why? Paths should always have trailing ones

**Review by stereomon — APPROVED** [review]

**Comment by k4emic** [comment]
@dereuromark 

I agree! Trailing slashes on a path indicates that it's a directory (instead of a file), which helps with readability. That being said, I don't think that submitting a PR to codeception to change this approach is likely to get accepted (even if we ignore how much time will be spent on it).

This is a pragmatic take on how we can enable running individual tests, by following established conventions.

**Review by k4emic — COMMENTED** [review]
Added comment detailing that paths should not end with slashes

**Comment by dereuromark** [comment]
But we could still try to submit PR here to them, maybe the next minor could Support the proper way

**Pull request merged**
